name: car-control
channels:
- conda-forge
- defaults
dependencies:
- python=3.11
- gymnasium
- stable-baselines3
- matplotlib
- opencv
- numpy
- pygame
- tensorboard
- moviepy
- pip
- pip:
  - random2
